### PR TITLE
Fix/#867

### LINKED ISSUE #867: data outside loop are lost on init
## Describe the bug
When you start a questionnaire with initial data, the data for collected variables outside loop are lost, we see a empty object instead `{}`

## To Reproduce
With behaviour "Paste" in storybook

## Expected behavior
We want to keep initial data

## Version where the bug appeared
The last one : `2.7.13`

## Browser where the bug was tested

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [x] Edge

### PR DESCRIPTION
**Pull request by QRuhier**
- [x] #867

### CODE REVIEW

File: src/utils/variables.ts [hunk 1]
```diff
@@ -12,17 +12,11 @@ export function getInitialVariableValue(
 		case 'CALCULATED':
 			return data[variable.variableType]?.[variable.name];
 		case 'COLLECTED':
-			const collectedData = data.COLLECTED;
-			let fromData;
-			if (collectedData && variable.name in collectedData) {
-				const { COLLECTED, FORCED } = collectedData[variable.name];
-				fromData = COLLECTED ?? FORCED;
-			}
+			let fromData = data.COLLECTED?.[variable.name]?.COLLECTED;
```
Comment (ddecrulle) [inline src/utils/variables.ts]: in fact this is a const ?

**Review by ddecrulle — APPROVED** [review]
