### PR TITLE
fix: handle missing for pageHasResponse

### LINKED ISSUE #858: improve support on `usePageHasReponse`
## Feature Description

Currently, the usePageHasReponse hook renders true only when a value is fulfilled in one component on the currentPage, with some exceptions for PairwiseLinks and Roundabout. However, it does not consider missing values as valid.

In situations where the currentPage lacks any input fields, such as in the case of a Sequence, the hook currently returns false.

## Use Case

In Queen, we currently display the continue button only if values are submitted. We propose a modification to show the continue button every time. However, in the scenario where `usePageHasReponse` is false, we intend to display a message asking the user if they are sure they want to proceed to the next page.

## Proposed Solution

I suggest enhancing the hook to consider missing values as well, returning true if they are submitted. Additionally, the hook should return true even if there are no input fields on the page.

## Priority

- [ ] Low
- [x] Medium
- [ ] High

### PR DESCRIPTION
**Pull request by Grafikart**
Ajout d'un élément dans le storybook pour suivre l'évolution de cette valeur et déboguer les comportements particuliers : 
image

Fix #858

### CODE REVIEW

File: src/use-lunatic/hooks/use-page-has-response.ts [hunk 1]
```diff
@@ -12,15 +12,30 @@ export function usePageHasResponse(
...
 		for (const component of components) {
 			// Some components are considered as "filled" by default
-			if (['PairwiseLinks', 'Roundabout'].includes(component.componentType)) {
+			if (
+				['PairwiseLinks', 'Roundabout', 'Sequence'].includes(
+					component.componentType
+				)
+			) {
+				return true;
+			}
```
Comment (ddecrulle) [inline src/use-lunatic/hooks/use-page-has-response.ts]: There is also subsequence that can have not input field. 

However in case of a sequence is displayed in the same page as an input component that will return a falsy `true`.

I think we should look if components has value (if no one return true) else return true only if one value is not empty

**Review by ddecrulle — CHANGES_REQUESTED** [review]

**Review by ddecrulle — APPROVED** [review]
